name: phd
channels:
  - defaults
  - anaconda
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.7.1
  - fonttools=4.60.1
  - freetype=2.13.3
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - jpeg=9f
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libkrb5=1.21.3
  - libpng=1.6.39
  - libpq=17.4
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numexpr=2.11.0
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.2
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.2
  - pillow=11.1.0
  - pip=25.2
  - pyparsing=3.2.0
  - pyqtgraph=0.13.7
  - pyserial=3.5
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - scipy=1.15.3
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - pyqt6==6.9.1
      - pyqt6-qt6==6.9.2
      - pyqt6-sip==13.10.2
